### PR TITLE
Partial spanish translation for ch15-04-rc.md

### PR DESCRIPTION
**Pull request by focusedguy**
I am an utopian contributor, 1124 words translated to spanish

### CODE REVIEW

**Comment by thecodix** [comment]
Hello,
I'm afraid we can no longer accept contributions that come from an automatic translated software, since the quality of the translations is not really helping more than translating the page using a software

Therefore I'll have to close this pull request

**Comment by focusedguy** [comment]
All right pal no problem, although I manually check every translation to make sure it’s correct. 

Next time I will do it 100% manually. 

By the way, do you know Spanish? Because I don’t know where was my mistake? 

Cheers mate.

**Comment by thecodix** [comment]
My spanish is sufficient to know that sentences are gramatically correct, but there is no programming knowledge behind to translate some technical terms on a consistent manner

Randomly picking up a chapter from a huge book and translating it out of context will add more trouble to the translation than we will benefit from it

**Comment by thecodix** [comment]
machine translated

**Pull request closed without merging**
