### PR TITLE
Translation of ch06-01-defining-an-enum.md(Part 2)

### PR DESCRIPTION
**Pull request by dbucci24**
second part of the Spanish translation of ch06-01-defining-an-enum.md

### CODE REVIEW

**Comment by thecodix** [comment]
I'll keep this PR open, you can add some commits to it to merge the full chapter, which I think is preferred

**Comment by dbucci24** [comment]
Can not you merge this one? I need to make PRs of around 1000 words for my work. I can finish the chapter in the next PR

**Comment by thecodix** [comment]
Hey, just curious about that 1000 words rule, there are some PRs that will be shorter and some others may be longer.

Sticking to a number of words won't work for shorter chapters as well, is there any reason why you're requested to have a fixed amount of words on each one?

Not the first time I see it here though :)

**Comment by thecodix** [comment]
If you want to stick with an arbitrary number of words, please then add a different commit message, where you explain a bit better what has changed (which sections) and not just partial translation, that way you can fit PR of any desired size

**Comment by thecodix** [comment]
Hey, I will merge this, but if you wan to stick with the 1000 words format, can you put bit more description in the PR message?
Instead of just Spanish translation of ch06-01-defining-an-enum.md
You could put Spanish translation of ch06-01-defining-an-enum.md, modified part blablabla

Obviously substituting blabla for the parts of the chapter you worked on :)

**Comment by dbucci24** [comment]
@thecodix ok!! I Will do that on the next PR :)

**Comment by thecodix** [comment]
Sounds perfect, thanks again for your time :)

**Pull request merged**
