### PR TITLE
Translation of ch-08-00, ch 09-00 and partial translation of ch 09-01 into spanish

### PR DESCRIPTION
**Pull request by siersod-utopian**

### CODE REVIEW

**Comment by thecodix** [comment]
Hello @siersod-utopian , thanks a lot for your time on the translation of this Rust book

One small question. If you see the original translation in english, you will see each line has a maximum of around 120 characters. Is it possibel that you update your changes and set this maximum as well for the spanish translation? It would help A LOT on the review and edition tasks

Thanks a lot! 🦀

**Comment by siersod-utopian** [comment]
Done. Thanks

**Comment by thecodix** [comment]
Hey, sorry to bother you again,

If you check when I'm reviewing the changes, the english section (in red) all lines have the same lenght aprox, while the spanish section which you translated (green one) does not

Can you fix it please?

Thanks!

screen shot 2018-02-19 at 19 45 58

**Comment by siersod-utopian** [comment]
Done again xD

the lines are longer because I had counted up to 120 characters, now with the new changes I see that they are about 80 characters per line

**Comment by thecodix** [comment]
Ufff very sorry then! I really didn't count myself, my fault!

Thanks for fixing it!

**Comment by thecodix** [comment]
After review, code is mostly a picture of google translate, which shouldn't be something fair for other translators and for the quality of the translation over time, therefore I'm inclined to revert the changes

**Comment by thecodix** [comment]
machine translated

**Pull request merged**
