### PR TITLE
Spanish translation of ch20-03-designing-the-interface.md file

### PR DESCRIPTION
**Pull request by michaelizer**

### CODE REVIEW

**Comment by thecodix** [comment]
Hello @michaelizer , could you please stick to a limit of around 80 characters per line, like in the english version? It will help a lot the review tasks!

Thanks a lot! 🦀

**Comment by michaelizer** [comment]
@thecodix Done, check it again and tell me what do you think?

**Comment by thecodix** [comment]
Like stated in the other task, please clarify if you are following a translation from google translate

**Comment by thecodix** [comment]
machine translated

**Pull request closed without merging**
