### PR TITLE
Partial spanish translation ch16-01-threads.md 1/2

### PR DESCRIPTION
**Pull request by chicooou**
Partial spanish translation ch16-01-threads.md 1/2
- Words: 1265
- Lines 1- 184

### CODE REVIEW

**Comment by thecodix** [comment]
Hey @chicooou , I leave you a comment here but this goes in general to the whole of the requests

It is very hard to provide a reliable review process when the number of pull requests is this big, there are almost 20 open right now and it affects other translators and collaboratos that are working on the project

Many people can't maintain a level of quality and produce a big amount of output, therefore I'm inclined to think you are using an automated tool and doing small tweaks to the result after. If I keep approving this changes, the quality of the project will resent, and the translation will result in people reading the book and wondering what things like 'la declaración de impresión del thread engendrado' mean

So please I would like you to clarify on this

Thanks anyway for the contributions

**Comment by chicooou** [comment]
Well, I had some problems with the meaning of "spawn" in context. I think maybe that was what caused this situation. if you observe also I opted to keep the word "thread". I do not know if you mean only that, or my contributions in general, but I would like to know if you consider that my contributions have the necessary quality, or if you prefer that I stop doing so. 

Ah and as a constructive criticism, the author or authors of the book should consider improving their use of punctuation signs. 🐙

**Comment by thecodix** [comment]
I would like to know if you have a programming background, and if up to some point have you played with Rust in the past particularly. I'm afraid this will be a question for contributors from now on

Translating a chapter is a big effort, since you have to be able to understand it and tell a story from it, not just write gramatically correct spanish sentences, which is my impression on many of the contributions over time

I'd spend more time accepting this changes and then comparing the text with the original, and making a story out from it, than starting a translation myself, so I'd rather wait until I have some more info on your background

If you don't have a sufficient background with programming, I would prefer you restrain from adding more contributions to the book, since as stated, translation will be gramatically correct but misleading in the efforts of teaching Rust to people

Concerning punctuation signs, some of the chapters you chose have not been 'frozen' in the original book and are still subject to changes by the editor, that may explain why 🦀

**Comment by chicooou** [comment]
Ah, yes of course, I studied until the second year of systems engineering. and unfortunately not, I have not used rust, I had only heard about the language.

And yes, I understand your point. It does not seem like a good idea to organize a work group. Choose a specific number of translators that you consider to have the necessary knowledge (from what I see you have enough to choose from) and based on that, distribute chapters and titles. Maybe create an issue for each chapter where the translators will establish the technical guidelines and so on.

Ah, and well, let me know if you would like to continue contributing. 🐌

**Comment by thecodix** [comment]
Wouldn't mind that you continue if there is a compromise to at least run the examples on each chapter you are translating on your local machine

The book is supposed to be an approach to Rust for new people, so if you are into translating it, you should let's say 'suffer' same inconveniences while running the examples in order to provide a better translation

I'm afraid I'll have to review previous translations of all users

**Pull request closed without merging**
