### PR TITLE
Partial ch14-02-publishing-to-crates-io.md (Part 1)

### PR DESCRIPTION
**Pull request by Osovich**
Around 1100 words translated, I have a question, tho. What's the actual spanish term I should use for Panic when it comes to programming?
Let me know if there's anything wrong!

### CODE REVIEW

**Comment by thecodix** [comment]
Hey, small question since will be interesting for rustaceans 🦀 

Why did you chose to start with chapter 14? Quite advanced this one

Not sure we have a spanish term which would be 100% correct for that, maybe you could check what's the term for the 1st edition of the book?

Thanks!

**Comment by Osovich** [comment]
Yeah, it's just Pánico, found a term used for kernels, in spanish people still use Panic, untranslated, for referring to that matter apparently. That's something I see a lot in school

I started with chapter 14 because everybody already took lower chapters, so i thought "well, nobody would try to take 14, it's really high up", and because i translate real slow, it would be a shame if i go with a chapter and when i come back somebody else started it already.

Is there something that needs fixing, tho? hahahaa!

**Comment by Osovich** [comment]
Found the term on the 1st edition, it's still pánico: https://goyox86.github.io/elpr/error-handling.html
It just sounds funny.

**Comment by thecodix** [comment]
Just wondered if you had some previous experience in Rust 🦀 since you started with an advanced chapter, that's all :)

**Comment by thecodix** [comment]
Closing translations of random chapters that were still open, in order to sync to translate full project

**Pull request closed without merging**
