### PR TITLE
Spanish translation of ch20-04-storing-threads.md file

### PR DESCRIPTION
**Pull request by michaelizer**

### CODE REVIEW

**Comment by thecodix** [comment]
Hey again @michaelizer , like in the other request, can you check its around 80 characters per line?

Thanks!

**Comment by michaelizer** [comment]
@thecodix done this one. I see josue33 has a lot of translation, he has been reported for machine translating.

**Comment by thecodix** [comment]
His contributions have been reverted, thanks for noticing as well

**Comment by thecodix** [comment]
Also, after checking this in detail, I'm also inclined to think you are using an automated translation tool for your translations, which will result in chaos on the overall translation quality

Therefore I will please ask you to clarify if you are using google translate for it or not

Thanks

**Comment by michaelizer** [comment]
Hey, I do not use google translate as my one and only translating tool (let me explain myself better). I have a few plugins installed in my browser like for example [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) and [Google Translator](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb) which make suggestions and corrections while translating on Visual Studio. This doesn't mean I use Google Translator as my 'main source' for translations, I work line by line, writing the translation my way and sometimes accepting they way they propose it to go. Tell me your opinion, I use this tools as a help when I get stuck and sometimes they correct mistakes I made.

**Comment by michaelizer** [comment]
@thecodix Grammarly even corrects some sentences in English (adds comas (,) or maybe some things the project owner missed) to give them more sense, this helps too (a lot sometimes hahaha).

**Comment by thecodix** [comment]
@michaelizer what I mean is, this is a quite complex book about a language which is not easy to follow

Starting a translation in chapter 20, without being involved before in the process of the translation, and without tangible contributions to projects in Rust, results in simply a correct spanish but lacks any awareness of what the message is about in the text

Therefore, I would prefer to have slower translations, but from people who understand the context of the book

Or maybe you could share what is your experience with Rust in the past? 🦀

**Comment by michaelizer** [comment]
I'm not THAT 'familiarized' with Rust but I've read about it in the past, I know it's similar to C, C++ (I learnt C my frists years at college). A friend was trying to teach me Rust, this is the only thing he could teach me back there. 
`fn main()` 
`{`
`     println("Hello World");`
`}`
I started from chapter 20 and going down, not to 'crash' with other people work. Everybody started from chapter 1 and sometimes happen that two (or more) translate the same file.

**Comment by michaelizer** [comment]
Anyway, you are the boss here. If you want me to read the whole book, start from scratch, learn Rust first or whatever, it's your call.

**Comment by thecodix** [comment]
What I mean is, this is a very complex topic, is not as trivial as translating an article, so around chapter 20 you may expect to have knowledge of 19 chapters so far.

Picking a chapter to not collide in other people's work is fair, but this is the kind of project where you need some background in the topic to understand it in english, even more if you plan to translate it, you have to be able to express the same but in an understandable and coherent way.

Myself I picked chapter 2 and I haven't gone through all of it, cause I don't use external tools, I try each part to be understandable and refer to the readers on the same terms congruently

Noone should just learning programming languages for the sake of a translation, but many concepts here are quite complex and good programming background is expected 

And I am really not the boss of anyone, just the fool that puts pieces together and tries to tell a story overall :)

**Comment by michaelizer** [comment]
Perfectly understood, I will start from zero on the second edition of the book and give a double check to any translation I made. Reading it after finishing may help to see if it makes sense (thinking out loud)

**Comment by michaelizer** [comment]
Please don't hurt my reputation [#114](https://github.com/progit/progit2-es/issues/114) 😞

**Comment by thecodix** [comment]
Note I raised the issue, cause that project in particular was being targeted by same translator that are now working here, but I didn't ask for any action in particular to be taken.

For different projects there may be different standards, and in some projects may be acceptable to make small deviations from google translate

**Comment by thecodix** [comment]
What I think would be interesting is take one of the first initial chapters and make a review of it (even if it's translated into spanish)
Which is something ideally I would like to do (with some help!) before the whole project finishes

Then you can make some comments about the parts of it that can be improved

**Comment by michaelizer** [comment]
Thank you, in my opinion, one thing is to use it as a crutch and another is to use it to do all the work for you. Good day mate.

**Comment by thecodix** [comment]
machine translated

**Comment by michaelizer** [comment]
??

**Pull request closed without merging**
