### PR TITLE
Partial (1/3) spanish translation ch11-01-writing-tests.md

### PR DESCRIPTION
**Pull request by jossue33**
Number of words: 1045
Line:1-212

### CODE REVIEW

**Comment by thecodix** [comment]
This is a comment for all PR about chapter 11-01, but you don't translate 'test', it stays the same through most part

I guess this is one of the tricky parts of translating something without knowing the context

**Comment by jossue33** [comment]
@thecodix  the 3 partial translations of writing test with the word "prueba" have already been edited by "test"

**Comment by thecodix** [comment]
Closed cause contents are just copied from google translate

**Comment by thecodix** [comment]
machine translated

**Pull request closed without merging**
