### PR TITLE
appendix-05-translation.md to spanish

### PR DESCRIPTION
**Pull request by Osovich**
All text in english translated, around 32 words. Let me know if there's anything wrong.

### CODE REVIEW

**Comment by thecodix** [comment]
Hey @Osovich again conflicts here, please ensure you have the latest version of my repo on your local repo, then proceed with the PR again 👍

**Comment by Osovich** [comment]
Oh, that's new, thanks for telling me hahahaha

**Comment by Osovich** [comment]
I think it's fixed now, but i couldn't see any new text, just one paragraph that was in english and spanish (i mean, it was there twice), it was the original english text, i'm new to this and i don't know what happened there haha

**Comment by thecodix** [comment]
Seems good to go

**Pull request merged**
