### PR TITLE
Partial spanish translation ch04-03-slices.md

### PR DESCRIPTION
**Pull request by chicooou**
Partial spanish translation ch04-03-slices.md
1333 words

### CODE REVIEW

**Comment by chicooou** [comment]
Yes, I thought about it too. In fact, in the following contributions I already placed it as slice. String slice looks like slice de cadena? string slice? or or some other?. do not accept or deny the other pull requests, I will make some modifications in relation to rebanadas de cadenas xD

**Comment by chicooou** [comment]
I've already made the changes :)

**Comment by thecodix** [comment]
In the beginning we discussed to have a reference page for this kind of controversial translation, may be a good time to come back to it and create a doc with the conventions we use from now on, wdyt?

**Comment by thecodix** [comment]
machine translated

**Pull request merged**
