### PR TITLE
partial spanish translation ch05-01-defining-structs.md

### PR DESCRIPTION
**Pull request by chicooou**
partial spanish translation ch05-01-defining-structs.md
1181 words
line 1 - 230

### CODE REVIEW

**Comment by thecodix** [comment]
Same goes for this one, can you merge locally with this branch, then PR again?

I can assist you if you don't find the way, but is just follow this 3 instructions

https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by chicooou** [comment]
I think I need help, I don't know how to do that. :S

**Comment by thecodix** [comment]
It seems a hard task, but it shouldn't :)

Follow this steps in your local repository:

```
git checkout master
git pull https://github.com/thecodix/book.git master
```
(here you will find conflicts, you may want to backup on git stash / local file(s) your changes, then solve conflicts)
`git push origin master`

**Comment by thecodix** [comment]
Lemme know if you still have trouble figuring out, I know is tricky every time there is a big merge

**Comment by chicooou** [comment]
Doing so will not affect contributions that have already been merged?

**Comment by chicooou** [comment]
Omg I felt like a hacker.xD  All right, I will close these pull requests and make them corrected.

**Comment by thecodix** [comment]
Perfect, thanks a lot!!

**Pull request closed without merging**
